# app/models.py
import os
import pickle
import pandas as pd
from tensorflow.keras.models import load_model

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
MODELS_DIR = os.path.join(ROOT, "models")

# Hydroponics ML assets
MODEL_FILE = os.path.join(MODELS_DIR, "hydro_model.pkl")
ENC_FILE = os.path.join(MODELS_DIR, "label_encoder.pkl")
LOOKUP_CSV = os.path.join(MODELS_DIR, "hydroponics.csv")  # full dataset with all species

# Plant disease detection model
DISEASE_MODEL_FILE = os.path.join(MODELS_DIR, "model.keras")  # your Keras model

def load_assets():
    # Hydroponics
    model = None
    le = None
    df = None

    # 1️⃣ Load full CSV if exists
    if os.path.exists(LOOKUP_CSV):
        try:
            df = pd.read_csv(LOOKUP_CSV)
            if "plant_name" in df.columns:
                df["plant_name"] = df["plant_name"].astype(str)
                # clean names once for all queries
                df['plant_clean'] = df['plant_name'].str.lower().str.strip()
                df['plant_clean'] = df['plant_clean'].str.replace(r'\(.*\)', '', regex=True).str.strip()
            print(f"✅ Loaded hydroponics CSV with {df.shape[0]} plants")
        except Exception as e:
            print("⚠️ Failed loading CSV:", e)
            df = None

    # 2️⃣ Load pickled model/encoder (optional)
    if os.path.exists(MODEL_FILE):
        try:
            with open(MODEL_FILE, "rb") as f:
                model = pickle.load(f)
        except Exception as e:
            print("⚠️ Failed loading hydroponics model:", e)
            model = None

    if os.path.exists(ENC_FILE):
        try:
            with open(ENC_FILE, "rb") as f:
                le = pickle.load(f)
        except Exception as e:
            print("⚠️ Failed loading encoder:", e)
            le = None

    # 3️⃣ Fallback tiny DF (if CSV fails)
        if df is None:
            df = pd.DataFrame([
                {"plant_name": "Tomato", "optimal_temp_c": 22.5, "optimal_ph": 5.55, "optimal_humidity": 69.3,
                 "optimal_nutrient_ppm": 331},
                {"plant_name": "Lettuce", "optimal_temp_c": 29.4, "optimal_ph": 6.45, "optimal_humidity": 52.5,
                 "optimal_nutrient_ppm": 618.8},
                {"plant_name": "Spinach", "optimal_temp_c": 26.8, "optimal_ph": 5.97, "optimal_humidity": 54.8,
                 "optimal_nutrient_ppm": 624.4},
                {"plant_name": "Basil", "optimal_temp_c": 25.2, "optimal_ph": 6.26, "optimal_humidity": 77,
                 "optimal_nutrient_ppm": 682.5},
                {"plant_name": "Cucumber", "optimal_temp_c": 19.9, "optimal_ph": 6.86, "optimal_humidity": 68.2,
                 "optimal_nutrient_ppm": 735.7},
                {"plant_name": "Strawberry", "optimal_temp_c": 19.9, "optimal_ph": 5.87, "optimal_humidity": 50.3,
                 "optimal_nutrient_ppm": 885.5},
                {"plant_name": "Bell Pepper", "optimal_temp_c": 18.7, "optimal_ph": 6.12, "optimal_humidity": 53,
                 "optimal_nutrient_ppm": 609.8},
                {"plant_name": "Eggplant", "optimal_temp_c": 28.4, "optimal_ph": 6.63, "optimal_humidity": 69.9,
                 "optimal_nutrient_ppm": 493.8},
                {"plant_name": "Mint", "optimal_temp_c": 25.2, "optimal_ph": 5.84, "optimal_humidity": 50.2,
                 "optimal_nutrient_ppm": 777.1},
                {"plant_name": "Kale", "optimal_temp_c": 26.5, "optimal_ph": 5.62, "optimal_humidity": 54.8,
                 "optimal_nutrient_ppm": 462.5},
                {"plant_name": "Broccoli", "optimal_temp_c": 18.2, "optimal_ph": 5.93, "optimal_humidity": 66.5,
                 "optimal_nutrient_ppm": 563.4},
                {"plant_name": "Cauliflower", "optimal_temp_c": 29.6, "optimal_ph": 5.74, "optimal_humidity": 70.8,
                 "optimal_nutrient_ppm": 347.1},
                {"plant_name": "Celery", "optimal_temp_c": 28, "optimal_ph": 6.89, "optimal_humidity": 69.6,
                 "optimal_nutrient_ppm": 315.2},
                {"plant_name": "Coriander", "optimal_temp_c": 20.5, "optimal_ph": 6.71, "optimal_humidity": 56.7,
                 "optimal_nutrient_ppm": 877.6},
                {"plant_name": "Chives", "optimal_temp_c": 20.2, "optimal_ph": 6.45, "optimal_humidity": 71.4,
                 "optimal_nutrient_ppm": 801.6},
                {"plant_name": "Dill", "optimal_temp_c": 20.2, "optimal_ph": 6.81, "optimal_humidity": 57.1,
                 "optimal_nutrient_ppm": 717.6},
                {"plant_name": "Parsley", "optimal_temp_c": 21.7, "optimal_ph": 6.71, "optimal_humidity": 59.8,
                 "optimal_nutrient_ppm": 545.4},
                {"plant_name": "Rosemary", "optimal_temp_c": 24.3, "optimal_ph": 5.78, "optimal_humidity": 72.4,
                 "optimal_nutrient_ppm": 404},
                {"plant_name": "Thyme", "optimal_temp_c": 23.2, "optimal_ph": 6.84, "optimal_humidity": 69.5,
                 "optimal_nutrient_ppm": 393.9},
                {"plant_name": "Sage", "optimal_temp_c": 21.5, "optimal_ph": 6.31, "optimal_humidity": 75.5,
                 "optimal_nutrient_ppm": 450.1},
                {"plant_name": "Oregano", "optimal_temp_c": 25.3, "optimal_ph": 6.71, "optimal_humidity": 69.7,
                 "optimal_nutrient_ppm": 629.5},
                {"plant_name": "Pea", "optimal_temp_c": 19.7, "optimal_ph": 6.84, "optimal_humidity": 67,
                 "optimal_nutrient_ppm": 728.8},
                {"plant_name": "Bean", "optimal_temp_c": 21.5, "optimal_ph": 5.98, "optimal_humidity": 52.8,
                 "optimal_nutrient_ppm": 696.1},
                {"plant_name": "Onion", "optimal_temp_c": 22.4, "optimal_ph": 5.67, "optimal_humidity": 61,
                 "optimal_nutrient_ppm": 468},
                {"plant_name": "Garlic", "optimal_temp_c": 23.5, "optimal_ph": 5.84, "optimal_humidity": 58,
                 "optimal_nutrient_ppm": 872.9},
                {"plant_name": "Chili", "optimal_temp_c": 27.4, "optimal_ph": 6.14, "optimal_humidity": 57.3,
                 "optimal_nutrient_ppm": 742.7},
                {"plant_name": "Papaya", "optimal_temp_c": 20.4, "optimal_ph": 6.73, "optimal_humidity": 79.2,
                 "optimal_nutrient_ppm": 632.6},
                {"plant_name": "Banana", "optimal_temp_c": 24.2, "optimal_ph": 6.79, "optimal_humidity": 61.8,
                 "optimal_nutrient_ppm": 667},
                {"plant_name": "Pumpkin", "optimal_temp_c": 25.1, "optimal_ph": 5.51, "optimal_humidity": 76.8,
                 "optimal_nutrient_ppm": 551.8},
                {"plant_name": "Melon", "optimal_temp_c": 18.6, "optimal_ph": 6.27, "optimal_humidity": 68.9,
                 "optimal_nutrient_ppm": 448.6},
                {"plant_name": "Okra", "optimal_temp_c": 25.3, "optimal_ph": 6.13, "optimal_humidity": 73.8,
                 "optimal_nutrient_ppm": 513.6},
                {"plant_name": "Beetroot", "optimal_temp_c": 20, "optimal_ph": 5.83, "optimal_humidity": 65.1,
                 "optimal_nutrient_ppm": 754.7},
                {"plant_name": "Carrot", "optimal_temp_c": 18.8, "optimal_ph": 5.68, "optimal_humidity": 67.3,
                 "optimal_nutrient_ppm": 308.6},
                {"plant_name": "Radish", "optimal_temp_c": 29.4, "optimal_ph": 6.01, "optimal_humidity": 64.8,
                 "optimal_nutrient_ppm": 369.6},
                {"plant_name": "Cabbage", "optimal_temp_c": 29.6, "optimal_ph": 6.91, "optimal_humidity": 55.9,
                 "optimal_nutrient_ppm": 327.6},
                {"plant_name": "Corn", "optimal_temp_c": 27.7, "optimal_ph": 5.98, "optimal_humidity": 71.7,
                 "optimal_nutrient_ppm": 324.4},
                {"plant_name": "Ginger", "optimal_temp_c": 21.7, "optimal_ph": 6.28, "optimal_humidity": 58.4,
                 "optimal_nutrient_ppm": 813.3},
                {"plant_name": "Turmeric", "optimal_temp_c": 19.2, "optimal_ph": 6.55, "optimal_humidity": 50.7,
                 "optimal_nutrient_ppm": 722.2},
                {"plant_name": "Methi", "optimal_temp_c": 26.2, "optimal_ph": 6.05, "optimal_humidity": 69.4,
                 "optimal_nutrient_ppm": 584.5},
                {"plant_name": "Fenugreek", "optimal_temp_c": 23.3, "optimal_ph": 6.96, "optimal_humidity": 55.3,
                 "optimal_nutrient_ppm": 358.7},
                {"plant_name": "Arugula", "optimal_temp_c": 19.5, "optimal_ph": 6.94, "optimal_humidity": 78.2,
                 "optimal_nutrient_ppm": 595},
                {"plant_name": "Zucchini", "optimal_temp_c": 23.9, "optimal_ph": 5.88, "optimal_humidity": 78.6,
                 "optimal_nutrient_ppm": 584.1},
                {"plant_name": "Mustard", "optimal_temp_c": 18.4, "optimal_ph": 6.25, "optimal_humidity": 77.4,
                 "optimal_nutrient_ppm": 403.9},
                {"plant_name": "Taro", "optimal_temp_c": 28.9, "optimal_ph": 5.95, "optimal_humidity": 61.1,
                 "optimal_nutrient_ppm": 560.3},
                {"plant_name": "Peanut", "optimal_temp_c": 21.1, "optimal_ph": 5.93, "optimal_humidity": 50.5,
                 "optimal_nutrient_ppm": 539.1},
                {"plant_name": "Sunflower", "optimal_temp_c": 26, "optimal_ph": 5.56, "optimal_humidity": 77.8,
                 "optimal_nutrient_ppm": 669.5},
                {"plant_name": "Peach", "optimal_temp_c": 21.7, "optimal_ph": 6.41, "optimal_humidity": 62.8,
                 "optimal_nutrient_ppm": 681.1},
                {"plant_name": "Pear", "optimal_temp_c": 24.2, "optimal_ph": 6.25, "optimal_humidity": 79,
                 "optimal_nutrient_ppm": 327.2},
                {"plant_name": "Apple", "optimal_temp_c": 24.6, "optimal_ph": 5.58, "optimal_humidity": 78.9,
                 "optimal_nutrient_ppm": 524.8},
                {"plant_name": "Grape", "optimal_temp_c": 20.2, "optimal_ph": 5.92, "optimal_humidity": 75.6,
                 "optimal_nutrient_ppm": 675.5},
                {"plant_name": "Orange", "optimal_temp_c": 29.6, "optimal_ph": 6.86, "optimal_humidity": 58.8,
                 "optimal_nutrient_ppm": 601.9},
                {"plant_name": "Lemon", "optimal_temp_c": 27.3, "optimal_ph": 5.86, "optimal_humidity": 61.6,
                 "optimal_nutrient_ppm": 813.9},
                {"plant_name": "Watermelon", "optimal_temp_c": 29.3, "optimal_ph": 5.72, "optimal_humidity": 75.5,
                 "optimal_nutrient_ppm": 695.2},
                {"plant_name": "Mango", "optimal_temp_c": 28.7, "optimal_ph": 6.23, "optimal_humidity": 59.5,
                 "optimal_nutrient_ppm": 397.8},
                {"plant_name": "Guava", "optimal_temp_c": 25.2, "optimal_ph": 6.98, "optimal_humidity": 55.1,
                 "optimal_nutrient_ppm": 342.3},
                {"plant_name": "Lychee", "optimal_temp_c": 29.1, "optimal_ph": 5.86, "optimal_humidity": 66.7,
                 "optimal_nutrient_ppm": 685.5},
                {"plant_name": "Jackfruit", "optimal_temp_c": 19.1, "optimal_ph": 6.51, "optimal_humidity": 78.1,
                 "optimal_nutrient_ppm": 315.9},
                {"plant_name": "Dragonfruit", "optimal_temp_c": 20.4, "optimal_ph": 6.64, "optimal_humidity": 70.9,
                 "optimal_nutrient_ppm": 651.5},
                {"plant_name": "Blueberry", "optimal_temp_c": 18.5, "optimal_ph": 5.86, "optimal_humidity": 67.1,
                 "optimal_nutrient_ppm": 864.1},
                {"plant_name": "Blackberry", "optimal_temp_c": 21.9, "optimal_ph": 6.59, "optimal_humidity": 52.9,
                 "optimal_nutrient_ppm": 645.3},
                {"plant_name": "Cherry", "optimal_temp_c": 22.7, "optimal_ph": 6.05, "optimal_humidity": 68.5,
                 "optimal_nutrient_ppm": 532.9},
                {"plant_name": "Pineapple", "optimal_temp_c": 21.3, "optimal_ph": 6.45, "optimal_humidity": 79.7,
                 "optimal_nutrient_ppm": 686},
                {"plant_name": "Avocado", "optimal_temp_c": 27.9, "optimal_ph": 6.45, "optimal_humidity": 54.2,
                 "optimal_nutrient_ppm": 575},
                {"plant_name": "Coconut", "optimal_temp_c": 22.3, "optimal_ph": 6.3, "optimal_humidity": 65.5,
                 "optimal_nutrient_ppm": 627.4},
                {"plant_name": "Paprika", "optimal_temp_c": 21.4, "optimal_ph": 5.64, "optimal_humidity": 76.3,
                 "optimal_nutrient_ppm": 864.9},
                {"plant_name": "Turnip", "optimal_temp_c": 24.5, "optimal_ph": 6.75, "optimal_humidity": 72.2,
                 "optimal_nutrient_ppm": 531.7},
                {"plant_name": "Spinach Red", "optimal_temp_c": 19.7, "optimal_ph": 5.98, "optimal_humidity": 70.9,
                 "optimal_nutrient_ppm": 876.7},
                {"plant_name": "Lettuce Romaine", "optimal_temp_c": 27.6, "optimal_ph": 5.78, "optimal_humidity": 71.1,
                 "optimal_nutrient_ppm": 843.2},
                {"plant_name": "Lettuce Iceberg", "optimal_temp_c": 18.9, "optimal_ph": 5.56, "optimal_humidity": 60.8,
                 "optimal_nutrient_ppm": 417.5},
                {"plant_name": "Cucumber Mini", "optimal_temp_c": 29.8, "optimal_ph": 6.39, "optimal_humidity": 58.8,
                 "optimal_nutrient_ppm": 341.6},
                {"plant_name": "Cucumber Long", "optimal_temp_c": 27.3, "optimal_ph": 6.52, "optimal_humidity": 74.3,
                 "optimal_nutrient_ppm": 360.5},
                {"plant_name": "Mint Spear", "optimal_temp_c": 20.4, "optimal_ph": 5.52, "optimal_humidity": 74.3,
                 "optimal_nutrient_ppm": 310.9},
                {"plant_name": "Mint Peppermint", "optimal_temp_c": 18.1, "optimal_ph": 6.27, "optimal_humidity": 76,
                 "optimal_nutrient_ppm": 356.7},
                {"plant_name": "Parsley Italian", "optimal_temp_c": 27.8, "optimal_ph": 5.84, "optimal_humidity": 77.4,
                 "optimal_nutrient_ppm": 709.8},
                {"plant_name": "Parsley Curly", "optimal_temp_c": 26.5, "optimal_ph": 6.47, "optimal_humidity": 65.3,
                 "optimal_nutrient_ppm": 342.7},
                {"plant_name": "Rosemary Blue", "optimal_temp_c": 26.7, "optimal_ph": 5.76, "optimal_humidity": 65,
                 "optimal_nutrient_ppm": 491.4},
                {"plant_name": "Basil Thai", "optimal_temp_c": 27.3, "optimal_ph": 6.54, "optimal_humidity": 73.9,
                 "optimal_nutrient_ppm": 806.9},
                {"plant_name": "Basil Sweet", "optimal_temp_c": 18.9, "optimal_ph": 6.08, "optimal_humidity": 69.5,
                 "optimal_nutrient_ppm": 314},
                {"plant_name": "Chili Green", "optimal_temp_c": 22.3, "optimal_ph": 6.91, "optimal_humidity": 71.1,
                 "optimal_nutrient_ppm": 788.7},
                {"plant_name": "Chili Red", "optimal_temp_c": 19.4, "optimal_ph": 5.71, "optimal_humidity": 73.9,
                 "optimal_nutrient_ppm": 469.1},
                {"plant_name": "Pepper Jalapeno", "optimal_temp_c": 28.4, "optimal_ph": 6.01, "optimal_humidity": 76.7,
                 "optimal_nutrient_ppm": 370.9},
                {"plant_name": "Pepper Habanero", "optimal_temp_c": 25.5, "optimal_ph": 5.67, "optimal_humidity": 60.1,
                 "optimal_nutrient_ppm": 718},
                {"plant_name": "Melon Honeydew", "optimal_temp_c": 22, "optimal_ph": 6.89, "optimal_humidity": 61.3,
                 "optimal_nutrient_ppm": 677.4},
                {"plant_name": "Melon Cantaloupe", "optimal_temp_c": 18.8, "optimal_ph": 6.82, "optimal_humidity": 52.8,
                 "optimal_nutrient_ppm": 826.5},
                {"plant_name": "Pumpkin Mini", "optimal_temp_c": 21.7, "optimal_ph": 5.89, "optimal_humidity": 67.3,
                 "optimal_nutrient_ppm": 741},
                {"plant_name": "Pumpkin Giant", "optimal_temp_c": 21.9, "optimal_ph": 6.49, "optimal_humidity": 51.1,
                 "optimal_nutrient_ppm": 782.1},
                {"plant_name": "Tomato Cherry", "optimal_temp_c": 26.8, "optimal_ph": 6.73, "optimal_humidity": 64,
                 "optimal_nutrient_ppm": 469.2},
                {"plant_name": "Tomato Heirloom", "optimal_temp_c": 25.7, "optimal_ph": 6.33, "optimal_humidity": 66.3,
                 "optimal_nutrient_ppm": 406.5},
                {"plant_name": "Tomato Roma", "optimal_temp_c": 28.6, "optimal_ph": 6.29, "optimal_humidity": 58.6,
                 "optimal_nutrient_ppm": 750.4},
                {"plant_name": "Strawberry Alpine", "optimal_temp_c": 23.7, "optimal_ph": 5.86,
                 "optimal_humidity": 67.7, "optimal_nutrient_ppm": 784.1},
                {"plant_name": "Strawberry Wild", "optimal_temp_c": 19.4, "optimal_ph": 5.64, "optimal_humidity": 50.9,
                 "optimal_nutrient_ppm": 894.3},
                {"plant_name": "Eggplant Round", "optimal_temp_c": 26.6, "optimal_ph": 6.85, "optimal_humidity": 51.1,
                 "optimal_nutrient_ppm": 547.6},
                {"plant_name": "Eggplant Long", "optimal_temp_c": 27.1, "optimal_ph": 6.85, "optimal_humidity": 74.7,
                 "optimal_nutrient_ppm": 523.2},
                {"plant_name": "Kale Curly", "optimal_temp_c": 24.7, "optimal_ph": 6.45, "optimal_humidity": 60.8,
                 "optimal_nutrient_ppm": 765.8},
                {"plant_name": "Kale Dinosaur", "optimal_temp_c": 27.3, "optimal_ph": 6.01, "optimal_humidity": 53.8,
                 "optimal_nutrient_ppm": 504.5},
                {"plant_name": "Lettuce Butterhead", "optimal_temp_c": 23.9, "optimal_ph": 6.02,
                 "optimal_humidity": 65.7, "optimal_nutrient_ppm": 858.5},
                {"plant_name": "Spinach Baby", "optimal_temp_c": 24.3, "optimal_ph": 6.59, "optimal_humidity": 73.1,
                 "optimal_nutrient_ppm": 815},
                {"plant_name": "Bok Choy", "optimal_temp_c": 23.1, "optimal_ph": 6.85, "optimal_humidity": 56.5,
                 "optimal_nutrient_ppm": 557.4},
                {"plant_name": "Swiss Chard", "optimal_temp_c": 18.3, "optimal_ph": 6.83, "optimal_humidity": 68.7,
                 "optimal_nutrient_ppm": 750.5},
                {"plant_name": "Brinjal", "optimal_temp_c": 19.3, "optimal_ph": 6.67, "optimal_humidity": 52.6,
                 "optimal_nutrient_ppm": 752.7},
                {"plant_name": "Physalis (Cape gooseberry)", "optimal_temp_c": 26.4, "optimal_ph": 5.69,
                 "optimal_humidity": 63, "optimal_nutrient_ppm": 1513},
                {"plant_name": "Mustard greens", "optimal_temp_c": 21, "optimal_ph": 5.88, "optimal_humidity": 64,
                 "optimal_nutrient_ppm": 875},
                {"plant_name": "Mustard (Leaf)", "optimal_temp_c": 21.3, "optimal_ph": 6.18, "optimal_humidity": 59,
                 "optimal_nutrient_ppm": 984},
                {"plant_name": "Spinach (Savoy)", "optimal_temp_c": 19.4, "optimal_ph": 5.97, "optimal_humidity": 63,
                 "optimal_nutrient_ppm": 955},
                {"plant_name": "Fennel", "optimal_temp_c": 24.4, "optimal_ph": 6.09, "optimal_humidity": 51,
                 "optimal_nutrient_ppm": 1196},
                {"plant_name": "Wasabi (Japanese horseradish)", "optimal_temp_c": 18.5, "optimal_ph": 6.07,
                 "optimal_humidity": 70, "optimal_nutrient_ppm": 1033},
                {"plant_name": "Elderberry (dwarf)", "optimal_temp_c": 26.3, "optimal_ph": 5.86, "optimal_humidity": 65,
                 "optimal_nutrient_ppm": 1409},
                {"plant_name": "Cucumber (Pickling)", "optimal_temp_c": 26.6, "optimal_ph": 5.87,
                 "optimal_humidity": 66, "optimal_nutrient_ppm": 1636},
                {"plant_name": "Tomato (Cherry)", "optimal_temp_c": 24.8, "optimal_ph": 5.91, "optimal_humidity": 70,
                 "optimal_nutrient_ppm": 1653},
                {"plant_name": "Lovage", "optimal_temp_c": 21.9, "optimal_ph": 6.17, "optimal_humidity": 59,
                 "optimal_nutrient_ppm": 1071},
                {"plant_name": "Cabbage (Green)", "optimal_temp_c": 24.4, "optimal_ph": 5.98, "optimal_humidity": 50,
                 "optimal_nutrient_ppm": 977},
                {"plant_name": "Basil (Sweet)", "optimal_temp_c": 22.3, "optimal_ph": 5.82, "optimal_humidity": 53,
                 "optimal_nutrient_ppm": 930},
                {"plant_name": "Microgreens (Sunflower)", "optimal_temp_c": 20.3, "optimal_ph": 6.19,
                 "optimal_humidity": 61, "optimal_nutrient_ppm": 904},
                {"plant_name": "Spinach (Smooth)", "optimal_temp_c": 18.8, "optimal_ph": 5.84, "optimal_humidity": 64,
                 "optimal_nutrient_ppm": 822},
                {"plant_name": "Pea (Sugar snap)", "optimal_temp_c": 23.9, "optimal_ph": 6.25, "optimal_humidity": 61,
                 "optimal_nutrient_ppm": 1138},
                {"plant_name": "Goji berry", "optimal_temp_c": 26.7, "optimal_ph": 5.71, "optimal_humidity": 75,
                 "optimal_nutrient_ppm": 1450},
                {"plant_name": "Chervil", "optimal_temp_c": 22.9, "optimal_ph": 5.93, "optimal_humidity": 60,
                 "optimal_nutrient_ppm": 1200},
                {"plant_name": "Broad bean", "optimal_temp_c": 22.4, "optimal_ph": 6.11, "optimal_humidity": 59,
                 "optimal_nutrient_ppm": 1041},
                {"plant_name": "Kale (Lacinato)", "optimal_temp_c": 20.9, "optimal_ph": 6, "optimal_humidity": 67,
                 "optimal_nutrient_ppm": 859},
                {"plant_name": "Cucumber (Slicing)", "optimal_temp_c": 23.8, "optimal_ph": 5.68, "optimal_humidity": 73,
                 "optimal_nutrient_ppm": 1433},
                {"plant_name": "Lime (dwarf)", "optimal_temp_c": 22.2, "optimal_ph": 5.91, "optimal_humidity": 64,
                 "optimal_nutrient_ppm": 955},
                {"plant_name": "Passionfruit (dwarf)", "optimal_temp_c": 26.7, "optimal_ph": 5.52,
                 "optimal_humidity": 69, "optimal_nutrient_ppm": 1401},
                {"plant_name": "Tarragon", "optimal_temp_c": 23, "optimal_ph": 5.93, "optimal_humidity": 53,
                 "optimal_nutrient_ppm": 926},
                {"plant_name": "Sea beet", "optimal_temp_c": 18.2, "optimal_ph": 6.23, "optimal_humidity": 64,
                 "optimal_nutrient_ppm": 1025},
                {"plant_name": "Chamomile", "optimal_temp_c": 20.9, "optimal_ph": 5.96, "optimal_humidity": 64,
                 "optimal_nutrient_ppm": 1137},
                {"plant_name": "Mallow", "optimal_temp_c": 22.3, "optimal_ph": 5.81, "optimal_humidity": 54,
                 "optimal_nutrient_ppm": 1078},
                {"plant_name": "Valerian", "optimal_temp_c": 24.1, "optimal_ph": 6.08, "optimal_humidity": 51,
                 "optimal_nutrient_ppm": 1067},
                {"plant_name": "Stevia", "optimal_temp_c": 19.8, "optimal_ph": 5.82, "optimal_humidity": 57,
                 "optimal_nutrient_ppm": 1077},
                {"plant_name": "Lettuce (Butterhead)", "optimal_temp_c": 20.6, "optimal_ph": 5.95,
                 "optimal_humidity": 66, "optimal_nutrient_ppm": 847},
                {"plant_name": "Cucumber (Mini)", "optimal_temp_c": 24.4, "optimal_ph": 5.52, "optimal_humidity": 70,
                 "optimal_nutrient_ppm": 1580},
                {"plant_name": "Cabbage (Red)", "optimal_temp_c": 20.2, "optimal_ph": 6.12, "optimal_humidity": 55,
                 "optimal_nutrient_ppm": 1088},
                {"plant_name": "Kale (Curly)", "optimal_temp_c": 18.2, "optimal_ph": 5.87, "optimal_humidity": 58,
                 "optimal_nutrient_ppm": 961},
                {"plant_name": "Grape (table, dwarf)", "optimal_temp_c": 26.4, "optimal_ph": 5.73,
                 "optimal_humidity": 64, "optimal_nutrient_ppm": 1677},
                {"plant_name": "Sweet pepper (mini)", "optimal_temp_c": 26, "optimal_ph": 5.9, "optimal_humidity": 69,
                 "optimal_nutrient_ppm": 1441},
                {"plant_name": "Bell pepper (yellow)", "optimal_temp_c": 26.7, "optimal_ph": 5.65,
                 "optimal_humidity": 69, "optimal_nutrient_ppm": 1653},
                {"plant_name": "Fava bean", "optimal_temp_c": 24.9, "optimal_ph": 6.12, "optimal_humidity": 62,
                 "optimal_nutrient_ppm": 1017},
                {"plant_name": "Microgreens (Pea)", "optimal_temp_c": 19.1, "optimal_ph": 5.88, "optimal_humidity": 67,
                 "optimal_nutrient_ppm": 918},
                {"plant_name": "Artichoke (globe)", "optimal_temp_c": 21.2, "optimal_ph": 6.15, "optimal_humidity": 50,
                 "optimal_nutrient_ppm": 1091},
                {"plant_name": "Microgreens (Amaranth)", "optimal_temp_c": 21.7, "optimal_ph": 6.05,
                 "optimal_humidity": 56, "optimal_nutrient_ppm": 963},
                {"plant_name": "Sorrel", "optimal_temp_c": 24, "optimal_ph": 6.1, "optimal_humidity": 61,
                 "optimal_nutrient_ppm": 1128},
                {"plant_name": "Fig (dwarf)", "optimal_temp_c": 25.7, "optimal_ph": 5.9, "optimal_humidity": 66,
                 "optimal_nutrient_ppm": 1357},
                {"plant_name": "Asparagus (baby)", "optimal_temp_c": 19.2, "optimal_ph": 6.01, "optimal_humidity": 67,
                 "optimal_nutrient_ppm": 1171},
                {"plant_name": "Melon (Honeydew)", "optimal_temp_c": 26.1, "optimal_ph": 5.7, "optimal_humidity": 75,
                 "optimal_nutrient_ppm": 1501},
                {"plant_name": "Moringa (young)", "optimal_temp_c": 19.5, "optimal_ph": 6.11, "optimal_humidity": 62,
                 "optimal_nutrient_ppm": 991},
                {"plant_name": "Papaya (dwarf)", "optimal_temp_c": 23.5, "optimal_ph": 5.6, "optimal_humidity": 66,
                 "optimal_nutrient_ppm": 1751},
                {"plant_name": "Micro basil", "optimal_temp_c": 19.7, "optimal_ph": 5.96, "optimal_humidity": 68,
                 "optimal_nutrient_ppm": 813},
                {"plant_name": "Pak choi (Baby bok choy)", "optimal_temp_c": 20.1, "optimal_ph": 6.08,
                 "optimal_humidity": 55, "optimal_nutrient_ppm": 965},
                {"plant_name": "Echinacea (young)", "optimal_temp_c": 23.1, "optimal_ph": 6.22, "optimal_humidity": 70,
                 "optimal_nutrient_ppm": 1101},
                {"plant_name": "Mizuna", "optimal_temp_c": 20.6, "optimal_ph": 5.94, "optimal_humidity": 70,
                 "optimal_nutrient_ppm": 979},
                {"plant_name": "Eggplant (Aubergine)", "optimal_temp_c": 26.1, "optimal_ph": 5.76,
                 "optimal_humidity": 70, "optimal_nutrient_ppm": 1355},
                {"plant_name": "Kumquat", "optimal_temp_c": 24.8, "optimal_ph": 5.79, "optimal_humidity": 62,
                 "optimal_nutrient_ppm": 1094},
                {"plant_name": "Celeriac", "optimal_temp_c": 20.1, "optimal_ph": 5.77, "optimal_humidity": 52,
                 "optimal_nutrient_ppm": 1182},
                {"plant_name": "Napa cabbage", "optimal_temp_c": 22.9, "optimal_ph": 5.74, "optimal_humidity": 54,
                 "optimal_nutrient_ppm": 1007},
                {"plant_name": "Pepper (Bell)", "optimal_temp_c": 25.9, "optimal_ph": 5.65, "optimal_humidity": 69,
                 "optimal_nutrient_ppm": 1399},
                {"plant_name": "Cilantro (Coriander)", "optimal_temp_c": 22.2, "optimal_ph": 6.32,
                 "optimal_humidity": 60, "optimal_nutrient_ppm": 924},
                {"plant_name": "Hyssop", "optimal_temp_c": 23.2, "optimal_ph": 5.8, "optimal_humidity": 53,
                 "optimal_nutrient_ppm": 949},
                {"plant_name": "Pepper (Chili)", "optimal_temp_c": 23.8, "optimal_ph": 5.78, "optimal_humidity": 65,
                 "optimal_nutrient_ppm": 1743},
                {"plant_name": "Mulberry (dwarf)", "optimal_temp_c": 23.2, "optimal_ph": 5.8, "optimal_humidity": 61,
                 "optimal_nutrient_ppm": 1224},
                {"plant_name": "Parsley (Flat-leaf)", "optimal_temp_c": 20.6, "optimal_ph": 5.8, "optimal_humidity": 59,
                 "optimal_nutrient_ppm": 850},
                {"plant_name": "Chaya (Tree spinach)", "optimal_temp_c": 21.4, "optimal_ph": 6.01,
                 "optimal_humidity": 57, "optimal_nutrient_ppm": 839},
                {"plant_name": "Tatsoi", "optimal_temp_c": 19.9, "optimal_ph": 5.82, "optimal_humidity": 62,
                 "optimal_nutrient_ppm": 953},
                {"plant_name": "Lovage", "optimal_temp_c": 23.8, "optimal_ph": 5.8, "optimal_humidity": 53,
                 "optimal_nutrient_ppm": 1143},
                {"plant_name": "Leek", "optimal_temp_c": 21.6, "optimal_ph": 5.87, "optimal_humidity": 64,
                 "optimal_nutrient_ppm": 1079},
                {"plant_name": "Lemongrass", "optimal_temp_c": 20.6, "optimal_ph": 6.21, "optimal_humidity": 58,
                 "optimal_nutrient_ppm": 964},
                {"plant_name": "Sweet corn (dwarf)", "optimal_temp_c": 24.6, "optimal_ph": 5.83, "optimal_humidity": 58,
                 "optimal_nutrient_ppm": 1197},
                {"plant_name": "Microgreens (Broccoli)", "optimal_temp_c": 19.1, "optimal_ph": 6.07,
                 "optimal_humidity": 62, "optimal_nutrient_ppm": 922},
                {"plant_name": "Kohlrabi", "optimal_temp_c": 19.2, "optimal_ph": 6.18, "optimal_humidity": 63,
                 "optimal_nutrient_ppm": 947},
                {"plant_name": "Angelica", "optimal_temp_c": 22, "optimal_ph": 6.29, "optimal_humidity": 58,
                 "optimal_nutrient_ppm": 1069},
                {"plant_name": "Collard greens", "optimal_temp_c": 24.5, "optimal_ph": 6.05, "optimal_humidity": 66,
                 "optimal_nutrient_ppm": 1025},
                {"plant_name": "Tomato (Beefsteak)", "optimal_temp_c": 23.1, "optimal_ph": 5.72, "optimal_humidity": 60,
                 "optimal_nutrient_ppm": 1798},
                {"plant_name": "Nasturtium (edible)", "optimal_temp_c": 19.8, "optimal_ph": 6.19,
                 "optimal_humidity": 69, "optimal_nutrient_ppm": 1139},
                {"plant_name": "Soybean (edamame)", "optimal_temp_c": 24.9, "optimal_ph": 5.94, "optimal_humidity": 50,
                 "optimal_nutrient_ppm": 1118},
                {"plant_name": "Raspberry", "optimal_temp_c": 23.7, "optimal_ph": 5.67, "optimal_humidity": 75,
                 "optimal_nutrient_ppm": 1546},
                {"plant_name": "Brussels sprouts", "optimal_temp_c": 21.8, "optimal_ph": 5.95, "optimal_humidity": 66,
                 "optimal_nutrient_ppm": 1017},
                {"plant_name": "Poppy (edible)", "optimal_temp_c": 20.7, "optimal_ph": 6.03, "optimal_humidity": 52,
                 "optimal_nutrient_ppm": 1027},
                {"plant_name": "Parsley (Curly)", "optimal_temp_c": 20.4, "optimal_ph": 6.39, "optimal_humidity": 61,
                 "optimal_nutrient_ppm": 1003},
                {"plant_name": "Bay leaf", "optimal_temp_c": 21.3, "optimal_ph": 5.81, "optimal_humidity": 58,
                 "optimal_nutrient_ppm": 945},
                {"plant_name": "Caper", "optimal_temp_c": 23.7, "optimal_ph": 5.71, "optimal_humidity": 55,
                 "optimal_nutrient_ppm": 1072},
                {"plant_name": "Turmeric (small)", "optimal_temp_c": 18.2, "optimal_ph": 6.12, "optimal_humidity": 64,
                 "optimal_nutrient_ppm": 1007},
                {"plant_name": "Lettuce (Romaine)", "optimal_temp_c": 20, "optimal_ph": 5.85, "optimal_humidity": 61,
                 "optimal_nutrient_ppm": 918},
                {"plant_name": "Shiso (Perilla)", "optimal_temp_c": 21.8, "optimal_ph": 5.82, "optimal_humidity": 54,
                 "optimal_nutrient_ppm": 1059},
                {"plant_name": "Melon (Cantaloupe)", "optimal_temp_c": 23.2, "optimal_ph": 5.63, "optimal_humidity": 65,
                 "optimal_nutrient_ppm": 1690},
                {"plant_name": "Endive", "optimal_temp_c": 19.3, "optimal_ph": 5.71, "optimal_humidity": 54,
                 "optimal_nutrient_ppm": 1120},
                {"plant_name": "Basil (Thai)", "optimal_temp_c": 21.2, "optimal_ph": 6.28, "optimal_humidity": 65,
                 "optimal_nutrient_ppm": 1032},
                {"plant_name": "Pea (Snow)", "optimal_temp_c": 24.4, "optimal_ph": 5.77, "optimal_humidity": 59,
                 "optimal_nutrient_ppm": 906},
                {"plant_name": "Aubergine (mini)", "optimal_temp_c": 22.3, "optimal_ph": 5.7, "optimal_humidity": 58,
                 "optimal_nutrient_ppm": 1123},
                {"plant_name": "Bayberry", "optimal_temp_c": 26.1, "optimal_ph": 5.8, "optimal_humidity": 69,
                 "optimal_nutrient_ppm": 1649},
                {"plant_name": "Rapini (Broccoli rabe)", "optimal_temp_c": 20.8, "optimal_ph": 5.74,
                 "optimal_humidity": 50, "optimal_nutrient_ppm": 1051},
                {"plant_name": "Savoury", "optimal_temp_c": 22.9, "optimal_ph": 5.94, "optimal_humidity": 52,
                 "optimal_nutrient_ppm": 1029},
                {"plant_name": "Lettuce (Oakleaf)", "optimal_temp_c": 21.7, "optimal_ph": 5.95, "optimal_humidity": 61,
                 "optimal_nutrient_ppm": 988},
                {"plant_name": "Cranberry", "optimal_temp_c": 23.3, "optimal_ph": 5.75, "optimal_humidity": 65,
                 "optimal_nutrient_ppm": 1476},
                {"plant_name": "Herb Robert", "optimal_temp_c": 20.4, "optimal_ph": 6.24, "optimal_humidity": 65,
                 "optimal_nutrient_ppm": 1011},
                {"plant_name": "Sweet potato (vining)", "optimal_temp_c": 20.2, "optimal_ph": 6.12,
                 "optimal_humidity": 75, "optimal_nutrient_ppm": 1266},
                {"plant_name": "Watercress", "optimal_temp_c": 18.3, "optimal_ph": 6.14, "optimal_humidity": 57,
                 "optimal_nutrient_ppm": 980},
                {"plant_name": "Purslane", "optimal_temp_c": 23.6, "optimal_ph": 5.91, "optimal_humidity": 66,
                 "optimal_nutrient_ppm": 1031},
                {"plant_name": "Microgreens (Radish)", "optimal_temp_c": 18.1, "optimal_ph": 6, "optimal_humidity": 55,
                 "optimal_nutrient_ppm": 913},
                {"plant_name": "Lemon (dwarf)", "optimal_temp_c": 21.4, "optimal_ph": 5.77, "optimal_humidity": 53,
                 "optimal_nutrient_ppm": 1124},
                {"plant_name": "Borage", "optimal_temp_c": 20.5, "optimal_ph": 6.25, "optimal_humidity": 53,
                 "optimal_nutrient_ppm": 1074},
                {"plant_name": "Calendula", "optimal_temp_c": 20.5, "optimal_ph": 5.89, "optimal_humidity": 59,
                 "optimal_nutrient_ppm": 1079},
                {"plant_name": "Tomato (Heirloom)", "optimal_temp_c": 23.1, "optimal_ph": 5.71, "optimal_humidity": 60,
                 "optimal_nutrient_ppm": 1476}
            ])

        df['plant_clean'] = df['plant_name'].str.lower().str.strip()

    # 4️⃣ Load disease detection model
    disease_model = None
    if os.path.exists(DISEASE_MODEL_FILE):
        try:
            disease_model = load_model(DISEASE_MODEL_FILE)
            print("✅ Disease detection model loaded successfully")
        except Exception as e:
            print("⚠️ Failed loading disease detection model:", e)

    return model, le, df, disease_model
